### ISSUE TITLE
토글버튼후 페이지이동시 유지

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#12]
메인페이지에서 토글버튼으로 memo를 끈다음
다른 페이지로 이동 했다가 다시 메인페이지로 오면
var memo_is_visible = true;
로 초기화 되므로
무조건 memo가 보여지게 됩니다.

질문:
memo를 끈다음 다른페이지로 이동하고 돌아오면 그 상태가 계속 유지되게 하고싶으면
어떻게 할수있나요?

감사합니다.

**Comment by yamoo9** [comment]
상태 변수 값을 서버 또는 사용자의 컴퓨터 로컬 스토리지에 저장 한 후 페이지가 로드될 때 
해당 값을 읽어들여 화면의 뷰를 처리해야 합니다.
