### ISSUE TITLE
연산자

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#13]
연산자로 값을 연산, 평가 한다고 하셨는데
평가는 어떤걸 말하나요?

**Comment by yamoo9** [comment]
예를 들어 산술 연산의 경우 아래와 같은 경우겠죠. ^^
조건 구문 내에서 x 변수 값이 숫자 9보다 큰 값인지를 비교 연산하여 평가하게 됩니다.

```js
var x = 9;
if ( x > 10 ) {
   console.log('x는 10보다 크다');
}
```
