### ISSUE TITLE
querySelector 가 getElementById보다 느린가요?

### ISSUE THREAD

**Issue by ujinhee** [yamoo9/JJ_CAMP_Fundamental#14]
아는 개발자분이 그렇다며, querySelector 말고 getElementById를 써달라고 하던데, 
정말 그런가요?

**Comment by yamoo9** [comment]
수업 시간에도 이야기 드렸지만 IE 8+ 이상 지원되는 프로젝트일 경우, 
`.querySelector()`를 사용하는 것이 좋습니다. ^^
