### ISSUE TITLE
장치 UI

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#16]
어떤 장치의 UI를 자바스크립트(웹)으로 만들기도 하나요?
키오스크나 버스안내판 이나 어떤 장치의 모니터링&제어 UI 같은거요..

예를들어 라즈베리파이(리눅스)에 온도센서, LED가 연결되있을때 그걸 컨트롤하고
반대로 현재온도를 자바스크립트가 받아서 표시 해주는게 가능한지..   보통 웹서버라면 request가 오면 클라이언트에 reponse를 주는건데.. 현재온도값을 받아서 표시해줄려면 어떻게 구현해야 할까요

**Comment by yamoo9** [comment]
**JavaScript API**로 구성된 **Kiosk Pro App**이 있는 것을 보면 가능할 듯 합니다. :-)

[kioskproapp.com](http://www.kioskproapp.com/javascriptapi)
