### ISSUE TITLE
교재 선별 부탁드립니다.

### ISSUE THREAD

**Issue by mulbee** [yamoo9/JJ_CAMP_Fundamental#17]
평일에 수업을 들을 수 있는 여건이 되지 않아 주말반을 듣고있습니다.
전에 한번 파트타임 강좌로도 스쿨 커리큘럼과 비슷하게 들을 수 있는지 여쭤봤던 수강생입니다.
파트타임 강좌도 주말만 있는것이 아닌 평일 저녁이 끼여있는 강좌가 많이 있는것을 확인했습니다.
사정상 평일 수업이 어려운 관계로 교재로라도 추후 다양한 공부를 더 진행 하고싶습니다.
4주차 수업때 강사님이 디자이너를 위한OOO등 얼마가지 못할 기술로 책 제목을 지어서 공부하게끔
만드는 책은 보지 않는 것이 좋다고 하셨는데 제가 아직 그런것을 선별할 안목을 가지고 있지 않습니다.
가능하시다면 자바스크립트와 좀 더 실전에서 응용할 수 있는 마크업 관련 교재추천 부탁드립니다.

**Comment by yamoo9** [comment]
현재 제가 진행하는 SCHOOL과 비슷한 커리큘럼을 모두 다루는 도서는 존재하지 않습니다.
워낙 도서가 다양하고, 저도 다 읽어본 것은 아니므로 추천해드릴 수 있는 폭이 좁네요 ^^;;

대신 원교수님 블로그에 올려진 링크를 추천드려봅니다. 스쿨에서 다루는 기초 파트에 해당하는
HTML5, CSS, JavaScript는 아래 링크 글을 따라가서 읽어보시면 어떨까 합니다. ^^

http://fromyou.tistory.com/581

---

현재 성공회대학교 소프트웨어공학과 외래교수로 재직하며 C#, 데이터베이스, HTML5 등을 강의하고 있는 원철연입니다.

얼마 전 HTML5, CSS and Javascript 책 한 권 분량(500 페이지, A4 기준)을 모두  본 블로그에 공개했습니다. 전체 목차가 일목요연하게 정리된 게 없어서 스스로 학습하는데 조금 어려움이 있을 것 같아서 엑셀 파일에 전체 리스트를 다음과 같이 만들었습니다.

[HTML5 CSS3 Javascript 책 공개링크.xlsx](http://fromyou.tistory.com/attachment/cfile23.uf@2757533A521374150372E6.xlsx)

필요하신 분들은 보시고 학습에 조금이라도 도움이 되시기 바랍니다.

그리고 본 내용을 가지고 비상업적인 목적으로 활용하시고자 하시는 단체나 선생님은 소속,성명(담당자),이메일, 
전화번호를 비밀로 남겨주시면 추후 HTML5 관련하여 업데이트가 있거나 강의시에 도움될 내용이 있을 경우 연락드리겠습니다. 감사합니다.
 
p.s : 현재 학과 과목에서 HTML5를 강의하고 있는데 새롭게 테스트하다보니 이 블로그에 올려진 자료의 작성시점에서 동작하던 속성, 기능들이 보안적인 이슈가 발생하거나 할 때 일부 지원이 안되거나 삭제되는 경우도 있는 것 같습니다. 아직 최종 표준이 되지 않아서 그런 것 같구요. 브라우저들도 매번 업데이트되기 때문에 그런 듯 합니다. 
학습하시는데 참고하세요.^^
