### ISSUE TITLE
속성 visibility

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#18]
function toggleMemoControl(){
  if ( memo_is_visible ) {
    memo.style.opacity = 0;
  } else {

위코드를

function toggleMemoControl(){
  if ( memo_is_visible ) {
    memo.style.visibility = hidden;
  } else {

이렇게 하니까 작동안하는데요 왜그런가요?

**Comment by yamoo9** [comment]
style 속성 객체에 css 속성을 연결하려 값을 걸정하려면 문자열 데이터를 설정해야 해요 "hidden" 설정하시면 될 거에요 ^^

**Comment by dooly9** [comment]
글쿤요.. 감사합니다.
