### ISSUE TITLE
status가 키워드인가요?

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#19]
변수를 status라고 했다가 안되서 한참 헤멨네요ㅜ

**Comment by yamoo9** [comment]
과거 `status`는 `window.status` 속성으로 윈도우 하단에 표시되는 상태 바의 메시지를 설정할 때 사용했습니다. 

하지만 오늘날 이는 사용되고 있지 않습니다. 대부분의 모던 웹 브라우저에서 하단 상태 표시바를 기본적으로 보이도록 설정하지 않고, 상태 변경 시에만 잠깐 보이도록 변경했기 때문인데요. (과거 상태 표시 줄이 악용 되던 경험 때문에)

변수로 `status` 이름을 사용하기 보다는 다른 이름을 사용하길 권장하지만, Chrome의 경우 아래 이미지처럼 개별 설정이 가능하기는 합니다. 웹 브라우저마다 차이가 있을 것으로 생각되네요. 가급적 변수 이름으로 `status` 그대로 사용하기 보다는 `currentStatus` 혹은 `visible_status` 등으로 사용하는 것을 권장드리고 싶습니다.


![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/Ugzocz3mB1UvwVGeab1xGKveViOUdb/New%2BTab%2B2017-03-27%2B08-11-05.jpg?Expires=1490656279&Signature=AQcdMx7gK59xFsVv2ifwwVNh8e1D0TFI8DBx0sJbyMdiPzl8dkvodaxAiVdvNgKODJL8YmD~DCFyW4~gpMR8V9KSKT5D8wlU0nMI4YNhSyuzhoXzIgDBRa4y5BZOTsBHGjvwOooiz~rmkrHiRDivFYDcr21M40SgEiH4bLHIiqL~l3Eoux7xT~nXnNfOA979Tt-zaCtFAZDuMiiskdiwDtbfSVEkC8RZylHk~wupKV-iBnIzL1Jvg-~jHM7eEAcT3jh~z5avd3BPtr9rEi1IFqp182lYrMfPAkBOxvinjaWuH3aswmhG1CHBaWKyI0m1Rml8u~3Mzl9fMr456Sj03Q__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

그리고 __JavaScript 키워드/예약어__ 는 다음과  같습니다.

```
abstract, arguments,
boolean, break, byte,
case, catch, char, class, const, continue, 
debugger, default, delete, do, double, 
else, enum, eval, export, extends,
false, final, finally, float, for, function, 
goto, ,
if, implements, import, in, instanceof, int, interface,
let, long, 
native, new, null,
package, private, protected, public, 
return,
short, static, super, switch, synchronized,
this, throw, throws, transient, true, try, typeof, 
var, void, volatile,
while, with, 
yield
```

**Comment by dooly9** [comment]
아래 소스인데 감추는건 되는데 보이기는 안되요. 크롬이구요..
변수 status를 currentStatus로 바꾸면 됩니다.
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>

<body lang='KO-KR'>
<p class='memo'>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>

<button type='button' class='button'>toggle</button>

<script>
var memo = document.querySelector('.memo');
var button = document.querySelector('.button');
var status = true;

button.onclick = function() {
    if (status) {
        memo.style.display = 'none';
        status = false;
    }
    else {
        memo.style.display = 'inherit';
        status = true;
    }
}
</script>
</body>
</html>
```
