### ISSUE TITLE
groupCollapsed / groupEnd 는 뭔가요?

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#20]
```
console.groupCollapsed('간단한` if 구문 연습');
if ( count === 10 ) {
   console.log("count is ten.");
} else {
   console.log("count isn't ten.");
}
console.groupEnd('간단한 if 구문 연습');
```

**Comment by yamoo9** [comment]
콘솔 화면에 뿌려줄 때 내부의 코드를 접힌 상태로 레이블을 만들어 출력해 줍니다.

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/jRfHE7zsqszBeeBEdjqYSPvA1g3GM5/groupCollapsed%2B%252F%2BgroupEnd%2B%25EB%258A%2594%2B%25EB%25AD%2594%25EA%25B0%2580%25EC%259A%2594%253F%2B%25C2%25B7%2BIssue%2B%252320%2B%25C2%25B7%2Byamoo9%252FJJ_CAMP_Fundamental%2B2017-03-27%2B14-34-56.jpg?Expires=1490679323&Signature=aleeiuNprKl9-AnVNqlqRIylskvqfp35Fi4hn~qXl350oMU~4ftp5IowNDo0tkuv6N3aD7C3gH9fRO5TwKmFRmbhxNIztqUrF67Yadic8-j9qekvUco0imH2FPESLt2tYrms1FwdD1FN2Cm9hf0zjyJh9srCpyzoKVxkFDFAwxV2YVEQmY0WJJHOdyRcP0IWGnSQBoJUSTBClDXRb1rAF4ZDkYwV2wsbvI0qSbUgrIws4i6qdVluuCAqDc320khjgIXFrOBWLuUhkJWl0Io6Yyt18PPGyV6CdMvETajItKb19zSQzCvEgjh6HdrUyMrsl81rxG6cYeamXy08q4XTEw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
