### ISSUE TITLE
setAttribute

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#21]
`list.setAttribute('style', 'display: none');`

이것과

`list.style.display='none'`

둘다 dom api 인가요?
그리고 저둘은 차이 없죠?

p.s 수업때 말씀드린 innerText와 textContent 차이 부탁합니다.

**Comment by yamoo9** [comment]
### XML DOM vs HTML DOM

DOM 방식의 차이 입니다.

__XML DOM__ 은 `.xml`, `.html`, `.htm` 모두 사용 가능하지만,
```js
list.setAttribute('style', 'display: none')
```

__HTML DOM__ 은 `.xml`에서는 사용할 수 없습니다.
```js
list.style.display='none'
```

---

### textContent VS innerText

textContent와 innerText의 차이점은 다음과 같습니다.

- `textContent`는 HTML 텍스트 코드를 단순히 텍스트로 출력한다.
- `textContent`는 모든 요소의 내용을 가져올 수 있다. 반면 `innerText`는 그렇지 않다.
- `innerText`는 `textContent`와 달리 숨겨진 요소들의 텍스트는 반환하지 않는다.
- `textContent` 속성은 IE 9+ 지원되지만, `innerText`는 모든 브라우저에서 지원된다.
