### ISSUE TITLE
뮤직플레이어요

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#22]
풀소스 공개인가요?
회전안되는거 확인 부탁드립니다. 혹시 Pause도 구현 가능하겠죠?
꼭 분석하고 이해해서 리펙토링 해보고 싶어요

그리고 ajax도 꼭해주시고 부하좀 많이 걸어주세요ㅎ
기본문법은 혼자서도 할수있으니까요
필요하면 예습이나 숙제도 내주시고..

**Comment by yamoo9** [comment]
코드를 확인해봐야 할 거 같습니다. 크로스 브라우징 이슈 해결한 후 다시 코드 공개할 께요.
그리고 Ajax 도 수업 때 할 수 있도록 모두가 열공 했으면 좋겠네요 ^^
