### ISSUE TITLE
가운데 위치시키기

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#23]
어떤 인트로페이지에 회사로고를 항상 정가운데(브라우저 크기를 움직여도) 위치시키고 싶은데요
단순 가로정렬은 `<center>로고</center>`로 하면 되는데 세로로 가운데 정렬시키는건
단순마크업이 없고 코드도 제각각이고 작동되고안되고 차이도 많은거 같아요 (제가 잘못알수도)
혹시 가로,세로 정가운데 위치시키는 좋은 코드나 방법이 있을까요?

**Comment by raijin8703** [comment]
음, <center></center>는 HTML5 부터는 더이상 지원되지 않는걸로 알고있습니다. 
만약 그 사이트가 XHTML 기반이라고 해도 센터보다는 CSS를 이용해 가운데 정렬시키는게 나을거라 생각합니다. 로고라면 아마 "<h1>로고(이미지 혹은 블록요소에 백그라운드 이미지로 들어가있겠죠?)</h1>"과 같이 되어있을거라 생각되는데여, 로고에 position:absolute 를 준뒤 top:50%; margin-top:-(로고 높이의 절반값)을 주는식으로 포지션과 offset 속성을 사용해서 정렬하면 되지 않을까요?

**Comment by yamoo9** [comment]
@raijin8703 님께서 정확히 말씀해주셔서 부연 설명은 안하겠습니다.
설명을 구현한 코드는 아래 링크를 참고 해보세요 ^^

https://jsfiddle.net/yamoo9/dj75vLd5/

**Comment by dooly9** [comment]
감사합니다!
