### ISSUE TITLE
cover 파일

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#24]
cover 파일명을 가져와서 미리 배열에 넣어주고 사용했는데
폴더에 cover파일이 5개든 10개든 동적으로 폴더내의 파일명을 가져올 수는 없나요?

그리고 복습하지말고 플레이어 마저 다 해주시면 안되요? ㄷ

**Comment by yamoo9** [comment]
Front-End 단에서 파일 명을 가져올 수는 없고, Back-End 단에서 처리해야 해요.
사용자 컴퓨터 환경에 접근하는 방법이 Front-End 단에서는 불가능합니다.
Server 환경에서는 가능하기에 Back-End 단에서 이를 처리하여 
JSON에 동적으로 리스트를 추가할 수 있어요.

우리 수업은 Front-End 단만 다루기 때문에 자동으로 처리할 수 없는 겁니다.
그리고 남은 3일 간은 jQuery를 학습해야 하기에 지금까지 배운 JavaScript 코드를
jQuery로 옮겨보면서 다시금 정리한 후, 시간적 여력이 될 때 Music Player를 완성해 볼 수 있어요.

**Comment by dooly9** [comment]
아 그렇군요!
감사합니다.
