### ISSUE TITLE
야무쌤 안녕하세요! 수강생 전태헌입니다.

### ISSUE THREAD

**Issue by rickyjeon** [yamoo9/JJ_CAMP_Fundamental#4]
안녕하세요! 
프론트엔드 수업부터 이번 jj camp까지 수업 듣고 있는 수강생 전태헌 이라고 합니다.
다름이 아니고 저번에 선생님께서 여쭤보신 남은 수업 진도에 대한 생각에 대해 말씀드리고 싶어 남깁니다.
제 생각으로는 남아있는 수업은 지금 배웠던 기본적인 것들을 응용하고 직접 쳐보는게 
의미가 있을 것 같다는 생각입니다.
저 같은경우는 개발자가 아니다보니 더 진도를 나가서 배우기 보다는 현재 배운것들을 
어떻게 더 잘 쓸 수 있을지 직접 쳐보고 코드에 좀 더 익숙해지는 게 좋을 것 같다는 생각이 듭니다.
제 의견이고 다른 수강생들의 의견을 수렴해서 수업 진행해주셨으면 좋겠습니다.
항상 열정적이고 세세하게 알려주셔서 감사합니다.

**Comment by yamoo9** [comment]
넵 태헌님 ^^ 의견 감사합니다.
몇몇 분들에게도 의사를 물어봤더니 뭔가를 만들어 보면서 익히는 것에 긍정적 이었습니다.
수업 때 다뤄볼 몇 가지 UI 컴포넌트를 다뤄보면서 자바스크립트를 익혀보도록 해요~
