### ISSUE TITLE
(git) fetch와 push는 뭔가요?

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#5]
git remote -v 했을때
origin이 두개나오고 (fetch), (push)라고 되있는데..

**Comment by yamoo9** [comment]
`git remote -v` 명령을 수행했을 때 다음과 같이 나오죠.

```sh
origin  https://github.com/yamoo9/JJ_CAMP_Fundamental.git (fetch)
origin  https://github.com/yamoo9/JJ_CAMP_Fundamental.git (push)
```

origin은 원격 저장소(Remote Repository)의 별칭으로 기본적으로 등록된 이름입니다.
(반드시 origin으로 사용할 필요는 없는데 일반적으로 origin이 사용됩니다)

push는 git 명령으로 내 컴퓨터 로컬 저장소의 데이터를 원격 저장소로 업로드 할 때 사용하는 것이고,
fetch는 반대로 원격 저장소 데이터를 내 컴퓨터 로컬 저장소로 다운로드 할 때 사용합니다. ^^
