### ISSUE TITLE
맥 추천 좀 부탁합니다.

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#6]
쓰시는 맥 모델은 뭔가요?

그리고 지금 맥 산다면 모델 추천 좀 부탁합니다.

노트북 거치대 링크나 검색어 좀 부탁합니다.

**Comment by yamoo9** [comment]
제가 사용하는 제품은 MacBook Pro (Retina, Mid 2012) 입니다.

키보드에 민감하시면 2015년 Macbook Pro 이전 모델이 어떨까 합니다.
(2015년 모델이나 제가 쓰는 2012년 모델이나 크게 차이 나지는 않습니다)

키보드에 민감하지 않으시면 [2016년 모델](http://www.apple.com/macbook-pro/)도 괜찮을 거 같습니다. ^^

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/hQnvAbMLrnikKYDXOi1zfwJqtvsinB/JJ_CAMP_Fundamental-2017-02-26-09-22-59.jpg?Expires=1488156065&Signature=b-gROuXx~wROfGYEGaLCEtZ~exgK4xMM8Vci2eHgxZfi0mDPP45wu2QgkYHOzkxeOiZ7jfkusfivnunT0hlkTGmdo1TE~04H25WO70TrYymCub21CWeI1HLwp8LcrEtacpWvnytqYikHbrlz2PgBaeKyLtjzrttC5pCKy-AoRuujLSPxHSimjUIbvxDhPH01MAtixeKakYWhrXzs3APs0lncW7AG2MnkRMmDc25sM-TQ1xZuyqPXte-5JVvj2YptD8UBX3TsfT-~F8JAIK5EAe6ZCBFr~G52sOYLLosnLJauT1dKDQHEfpAi-x2bn0NAWfUegjJuSmf6yIOKToRzbQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

---

그리고 노트북 거치대는... 제가 사용하는 건 수강생에게 선물 받은 거라서... 제품 명을 정확히 모르겠습니다. ㅠㅡㅠ
찾아보면 다양한 제품이 나오는데 아래 링크의 제품은 독특하고, 휴대성 등 여러 면에서 괜찮아 보이네요.

[The Geeks](http://blog.naver.com/PostView.nhn?blogId=kissi3oy&logNo=220741441950&parentCategoryNo=&categoryNo=35&viewDate=&isShowPopularPosts=true&from=search)

![](http://postfiles7.naver.net/20160620_166/kissi3oy_14664022943764bI73_JPEG/%B6%F3%B7%EB_IMG_5342.jpg?type=w966)

**Comment by dooly9** [comment]
감사합니다.  스탠드 구입했습니다
