### ISSUE TITLE
설치한 git desktop 프로그램은 github만 되나요?

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#7]
gitlab도 되나요?

**Comment by yamoo9** [comment]
저는 GitLab을 사용하고 있지 않아 정확하지는 않습니다만... 정보를 찾아보니 가능하지 않을까 합니다.

GitLab의 [Our Application Partners, GUI Git Clients](https://about.gitlab.com/applications/#gui-git-clients) 링크를 살펴보면 GitHub Desktop도 파트너로 보입니다.

[Using GitLab on Windows](https://www.youtube.com/watch?v=fGiQIJczdFc) 유투브 영상도 한번 살펴보세요. GitHub Desktop을 사용하는 듯 하네요.
