### ISSUE TITLE
마케팅 랜딩페이지가 뭔가요?

### ISSUE THREAD

**Issue by dooly9** [yamoo9/JJ_CAMP_Fundamental#8]
냉무

**Comment by yamoo9** [comment]
### 랜딩 페이지 마케팅 이란?

LPO(Landing Page Optimization)을 말하며 고객이 랜딩 페이지에 도달했을 때 원하는 내용이 보이지 않거나 웹사이트 내비게이션, 검색 기능 등이 갖춰지지 않았다면 대부분은 찾는 것을 포기하고 웹 사이트를 떠납니다.

이런 문제를 해결하고자 고객이 다른 곳으로 떠나지 않도록 랜딩 페이지에서 목적 페이지로 이동하게 하는 최소한의 기법이 등장합니다. 랜딩 페이지의 목적은 불필요하거나 혼란을 야기하는 정보를 최대한 배제하고 방문자가 목적을 빠르게 달성할 수 있도록 하는 기법입니다.

#[랜딩 페이지 최적화](https://ko.wikipedia.org/wiki/%EB%9E%9C%EB%94%A9_%ED%8E%98%EC%9D%B4%EC%A7%80_%EC%B5%9C%EC%A0%81%ED%99%94)
